authors:
  vedranm:
    name: Vedran Miletić
    description: Free and open source software enthusiast
    avatar: https://github.com/vedranmiletic.png
    url: https://vedran.miletic.net/
  domargan:
    name: Domagoj Margan
    description: Free and open source software enthusiast
    avatar: https://github.com/domargan.png
    url: https://domargan.net/
